name: server
description: A simple dart frog project
version: 0.1.1
environment:
  sdk: '>=3.0.0'

publish_to: none

dependencies:
  dart_frog: ^1.0.0
  intl: ^0.19.0
  collection: ^1.18.0
  http: ^1.3.0
  dotenv: ^4.2.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  test: ^1.25.4
  mocktail: ^1.0.3
  lints: ^3.0.0